### ISSUE TITLE
New build for Docker Hub

### ISSUE THREAD

**Issue by 501st-alpha1** [yspreen/sqlcipher#2]
Could we get a new build of this image on Docker Hub at some point?

I and other users ran into an error when [exporting data from Signal Desktop](https://github.com/signalapp/Signal-Desktop/issues/1013#issuecomment-1815829200) which indicated the version of sqlcipher from this image was too old.

(I cloned the repo and built the image myself and it worked fine, so no code changes are necessary, just needs a rebuild.)

**Comment by yspreen** [comment]
Up to date now.
